// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnvxAdDtx-Gc1iYQTCIMTGhtTALEcgDC8',
    appId: '1:144353908734:web:ce14c2010c2b08003bd2af',
    messagingSenderId: '144353908734',
    projectId: 'database-62a17',
    authDomain: 'database-62a17.firebaseapp.com',
    storageBucket: 'database-62a17.firebasestorage.app',
    measurementId: 'G-441YPH2RQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC5m2ODD25H-FgSuUI8sXIgwAWbJyIPYo',
    appId: '1:144353908734:android:6966aaca9adbca653bd2af',
    messagingSenderId: '144353908734',
    projectId: 'database-62a17',
    storageBucket: 'database-62a17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTHoIvKjIfzPV91yhdW6Qg0Q56i9MZFNA',
    appId: '1:144353908734:ios:7bbcd91a638b3ed03bd2af',
    messagingSenderId: '144353908734',
    projectId: 'database-62a17',
    storageBucket: 'database-62a17.firebasestorage.app',
    iosBundleId: 'com.example.itec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTHoIvKjIfzPV91yhdW6Qg0Q56i9MZFNA',
    appId: '1:144353908734:ios:7bbcd91a638b3ed03bd2af',
    messagingSenderId: '144353908734',
    projectId: 'database-62a17',
    storageBucket: 'database-62a17.firebasestorage.app',
    iosBundleId: 'com.example.itec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnvxAdDtx-Gc1iYQTCIMTGhtTALEcgDC8',
    appId: '1:144353908734:web:29ee2c43228bad9c3bd2af',
    messagingSenderId: '144353908734',
    projectId: 'database-62a17',
    authDomain: 'database-62a17.firebaseapp.com',
    storageBucket: 'database-62a17.firebasestorage.app',
    measurementId: 'G-ZKZ843P4D9',
  );
}
